### ISSUE TITLE
Trading agent

### ISSUE THREAD

**Issue by AhmMontasser** [ZhengyaoJiang/PGPortfolio#11]
Hello great team,

is there a trading agent already built to trade live using the saved trained model ? 

I would be interested to help either by building or by improving existing.

Regards,

**Comment by ZhengyaoJiang** [comment]
Greetings,
Yes, our team is doing live-trading now. Of course, in long term, we need more engineers and expert of quantitative trading/ machine learning to expand our business.
While currently, we do not eager to recruit new members since the live-trading framework has already been built and tested for quite a while.
If you want to join us in future(maybe several months later), you could try to contribute to this open source project first to get familiar with the framework.

Regards
Zhengyao

**Comment by AhmMontasser** [comment]
Thank you

**Comment by AhmMontasser** [comment]
I have been trying to code my a live trader, but 1 issue facing me is how to get live poloniex data while using the classes already implemented, of course i can hardcode generate_history_matrix to create the
[3,11,31] history data every tick manually but i am asking for the right way of doing it since i didn't understand it.

Regards

**Comment by huminpurin** [comment]
I'm also trying to use the trained model for live trading. the problem is i cant find which part of program generates the actions of buying/selling signal. Any help would be great. Thanks!

**Comment by ZhengyaoJiang** [comment]
> cant find which part of program generates the actions of buying/selling signal

Basically, the nnagent class output the portfolio weights. You can subtract two portfolio vector to get the transaction vector.
