### ISSUE TITLE
Bug in implementation of mu

### ISSUE THREAD

**Issue by kumkee** [ZhengyaoJiang/PGPortfolio#25]
A discussion with @ziofil [here](https://github.com/ZhengyaoJiang/PGPortfolio/issues/22) leads to a discovery of the bug of the implementation of how mu is calculated.

mu during training was implemented at: https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/learn/nnagent.py#L176-L197
during backtest it was:
https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/tools/trade.py#L39-L53

**Comment by ZhengyaoJiang** [comment]
I don't think that's a bug.
Actually, I prefer to change the article to make y_t as future price rather than relative price.

**Comment by kumkee** [comment]
If like @ZhengyaoJiang said, .input_num-1 representing t, the current time in the batch, then this is not a bug.

**Comment by DexHunter** [comment]
`input_num` is `batch_size`. I think @ZhengyaoJiang has a different interpretation of y_t. However in #22 ,  as @kumkee and @ziofil agreed, the mu_t is a function of y_t rather than y_{t+1}. However in the [code](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/learn/nnagent.py#L24-L25) `future_omega` is calculated by w_t * y_{t+1}. So that's why there seems to be a problem, or am I misunderstanding anything? Thanks  in advance for any help.

> In summary: the loss for the decision w_t taken at time t should be computed as the negative log rate of return mu_t(w_t \cdot y_{t+1}), where mu_t is a function of w_{t-1}, y_t and w_t, is this all correct?

> All correct. Thank you for your careful reading of our poorly written paper. 
We will improve it with this particular confusion in mind for the next version.
