### ISSUE TITLE
using volume information

### ISSUE THREAD

**Issue by ziofil** [ZhengyaoJiang/PGPortfolio#66]
Has anyone been experimenting with volume information? I've tried adding it as another feature (as if it was another layer in addition to close, high, low) and normalizing it to its last values, a bit like we do for the closing prices. It doesn't seem to help very much, perhaps I'm not doing it right?

**Comment by trevorprater** [comment]
I’ve also not had much luck using volume as a fourth feature.

**Comment by schmidtj** [comment]
I have made similar changes and haven't had luck with gaining an advantage by using volume.  I've changed the normalization to use the last value for each feature, this seems to work with the prices (close, high, low), but does not result in any benefit for volume.  I thought that it might be due to the volume changing more drastically than prices, so I tried scaling and standardization, to no avail.

**Comment by lytkarinskiy** [comment]
I think that it's possible to use volume information if we have separate buy/sell volumes, in this case we can use buy/sell volumes ratio as bull/bear marker. But total volume doesn't tell us anything additional I think.

**Comment by ZhengyaoJiang** [comment]
@ziofil @trevorprater @schmidtj 
Thanks for sharing information about this.
We also didn't find a way to properly incorporate volume information until now.

**Comment by akaniklaus** [comment]
@lytkarinskiy It should tell something additional actually. If volume is high and price drops, that would mean the sell volume is higher; vica, versa. Anybody tried having ADOSC (Chaikin A/D Oscillator) or MFI (Money Flow Index) indicators of TA-Lib, which uses volume as an input as features? Did anybody also tried multi-resolution (multi-period) features in the input vector? @ziofil @trevorprater @schmidtj
